export const siteConfig = {
  name: 'OpenSpace',
  description: 'La première plateforme cloud pensée pour les builders africains',
  url: 'https://openspace.cm',
  ogImage: 'https://openspace.cm/og.png',
  links: {
    twitter: 'https://twitter.com/openspace',
    github: 'https://github.com/openspace',
    documentation: 'https://docs.openspace.cm',
    email: 'support@openspace.cm',
  },
  creator: 'AURORA IT Corporation',
}

export const plans = [
  {
    id: 'starter',
    name: 'Starter',
    description: 'Parfait pour débuter',
    price: 2000,
    currency: 'FCFA',
    ram: '512 Mo',
    cpu: 0.5,
    storage: 5,
    domains: 1,
    features: [
      '512 Mo RAM',
      '0.5 vCPU',
      '5 Go SSD',
      '1 domaine inclus',
      'SSL gratuit',
      'Support email',
    ],
    popular: false,
  },
  {
    id: 'dev',
    name: 'Dev',
    description: 'Pour les développeurs',
    price: 3500,
    currency: 'FCFA',
    ram: '512 Mo',
    cpu: 1.0,
    storage: 10,
    domains: 5,
    features: [
      '512 Mo RAM',
      '1 vCPU',
      '10 Go SSD',
      '5 domaines inclus',
      'SSL gratuit',
      'Support prioritaire',
      'Statistiques avancées',
    ],
    popular: true,
  },
  {
    id: 'pro',
    name: 'Pro',
    description: 'Pour les projets professionnels',
    price: 6000,
    currency: 'FCFA',
    ram: '1 Go',
    cpu: 2.0,
    storage: 20,
    domains: null,
    features: [
      '1 Go RAM',
      '2 vCPU',
      '20 Go SSD',
      'Domaines illimités',
      'SSL gratuit',
      'Support 24/7',
      'API Complète',
      'Webhooks',
    ],
    popular: false,
  },
  {
    id: 'business',
    name: 'Business',
    description: 'Pour les équipes',
    price: 12000,
    currency: 'FCFA',
    ram: '2 Go',
    cpu: 4.0,
    storage: 40,
    domains: null,
    features: [
      '2 Go RAM',
      '4 vCPU',
      '40 Go SSD',
      'Domaines illimités',
      'SSL gratuit',
      'Support 24/7 prioritaire',
      'API Premium',
      'Webhooks',
      'Stockage étendu',
    ],
    popular: false,
  },
]
